# Generated by Django 3.1.3 on 2020-11-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='thumbnail',
            field=models.ImageField(default=1, upload_to='categories'),
            preserve_default=False,
        ),
    ]
