# Generated by Django 3.1.3 on 2020-11-07 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201107_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='desc',
        ),
    ]
