# Generated by Django 3.1.3 on 2020-11-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_offer_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='desc',
            field=models.TextField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
