# Generated by Django 3.1.3 on 2020-11-13 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_order_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='size',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(choices=[('sm', 'Small'), ('l', 'Large'), ('xl', 'Extra Large'), ('xxl', 'Extra Extra Large')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
